/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaymentDetails } from "./PaymentDetails";
import { PaymentDetailsCountArgs } from "./PaymentDetailsCountArgs";
import { PaymentDetailsFindManyArgs } from "./PaymentDetailsFindManyArgs";
import { PaymentDetailsFindUniqueArgs } from "./PaymentDetailsFindUniqueArgs";
import { CreatePaymentDetailsArgs } from "./CreatePaymentDetailsArgs";
import { UpdatePaymentDetailsArgs } from "./UpdatePaymentDetailsArgs";
import { DeletePaymentDetailsArgs } from "./DeletePaymentDetailsArgs";
import { Order } from "../../order/base/Order";
import { PaymentDetailsService } from "../paymentDetails.service";
@graphql.Resolver(() => PaymentDetails)
export class PaymentDetailsResolverBase {
  constructor(protected readonly service: PaymentDetailsService) {}

  async _paymentDetailsItemsMeta(
    @graphql.Args() args: PaymentDetailsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PaymentDetails])
  async paymentDetailsItems(
    @graphql.Args() args: PaymentDetailsFindManyArgs
  ): Promise<PaymentDetails[]> {
    return this.service.paymentDetailsItems(args);
  }

  @graphql.Query(() => PaymentDetails, { nullable: true })
  async paymentDetails(
    @graphql.Args() args: PaymentDetailsFindUniqueArgs
  ): Promise<PaymentDetails | null> {
    const result = await this.service.paymentDetails(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PaymentDetails)
  async createPaymentDetails(
    @graphql.Args() args: CreatePaymentDetailsArgs
  ): Promise<PaymentDetails> {
    return await this.service.createPaymentDetails({
      ...args,
      data: {
        ...args.data,

        order: args.data.order
          ? {
              connect: args.data.order,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PaymentDetails)
  async updatePaymentDetails(
    @graphql.Args() args: UpdatePaymentDetailsArgs
  ): Promise<PaymentDetails | null> {
    try {
      return await this.service.updatePaymentDetails({
        ...args,
        data: {
          ...args.data,

          order: args.data.order
            ? {
                connect: args.data.order,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaymentDetails)
  async deletePaymentDetails(
    @graphql.Args() args: DeletePaymentDetailsArgs
  ): Promise<PaymentDetails | null> {
    try {
      return await this.service.deletePaymentDetails(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Order, {
    nullable: true,
    name: "order",
  })
  async getOrder(
    @graphql.Parent() parent: PaymentDetails
  ): Promise<Order | null> {
    const result = await this.service.getOrder(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
